spring:
  main:
    web-application-type: none

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9091/eureka,http://localhost:9092/eureka

feign:
  okhttp:
    enabled: true