server:
  port: 9099

spring:
  cloud:
    config:
      server:
        git:
          #          uri: E:\All PROGRAMS\microservicesss\configrepo
          uri: https://itishree-baliarsingh-dev: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@github.com/itishree-baliarsingh-dev/suzkiconfigrepo.git
          default-lebel: feature-dev
          refresh-rate: 80
  security:
    user:
      name: itishree
      password: sairam123