server:
  port: 8080

spring:
  application:
    name: distributor-network

  profiles:
    active: dev

management:
  endpoint:
    refresh:
      enabled: true
  endpoints:
    web:
      exposure:
        include: refresh
